### ISSUE TITLE
left join dropping records with NULL key

### ISSUE THREAD

**Issue by exaatto** [cwida/duckdb#1172] opened 2020-12-01 07:23 UTC
We came across this problem in our production and managed to make a minimal example as follows.

```sql
drop table if exists t1;
drop table if exists t2;
create table t1 (id string);
create table t2 (id string);

insert into t1 values
(NULL);

insert into t2 values
(1),
(1);

select * from t1 left join t2 on t1.id = t2.id;

insert into t2 values
(1);

select * from t1 left join t2 on t1.id = t2.id;
```

The first join statement produces on record of `NULL, NULL` while the second produces nothing.

```bash
./build/release/duckdb foo  < left-join-drop-value-bug.sql
┌────┬────┐
│ id │ id │
├────┼────┤
│    │    │
└────┴────┘
```

What's interesting is that this left join on NULL is not always dropping records. It's related to row count of lhs none NULL keys. In the above example with 1 lhs NULL record and 0 none NULL record, the NULL record is dropped when there are > 2 rhs records. When there are 1 lhs none NULL record, the NULL record is dropped when there are > 4 rhs records, and then 3->6, 4->8...

Here is an example of 3->6.
```sql
drop table if exists t1;
drop table if exists t2;
create table t1 (id string);
create table t2 (id string);

insert into t1 (id) values
(1),
(1),
(NULL);

insert into t2 (id) values
(1),
(1),
(1),
(1),
(1),
(1);

select * from t1 left join t2 on t1.id = t2.id;

insert into t2 (id) values
(1);

select * from t1 left join t2 on t1.id = t2.id;
```

We have not dig into the code, but it seems to be related to the optimizer that pruning the wrong branches?

**Comment by Mytherin** [comment] 2020-12-01 09:02
Thanks for the report! I can confirm the issue (and have just fixed it: #1173).

The problem was that the optimizer would switch to using a `RIGHT` join (instead of a `LEFT` join) when t2 grew in size, see the explain output:

```sql
D drop table if exists t1;
D drop table if exists t2;
D create table t1 (id string);
D create table t2 (id string);
D 
D insert into t1 values (NULL);
D 
D insert into t2 values (1), (1);
D 
D explain select * from t1 left join t2 on t1.id = t2.id;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐                             
│         HASH_JOIN         │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│            LEFT           ├──────────────┐              
│           id=id           │              │              
└─────────────┬─────────────┘              │                                           
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│          SEQ_SCAN         ││          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             t1            ││             t2            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            ││             id            │
└───────────────────────────┘└───────────────────────────┘                             
D 
D insert into t2 values (1);
D 
D explain select * from t1 left join t2 on t1.id = t2.id;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐                             
│         PROJECTION        │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│             id            │                             
│             id            │                             
└─────────────┬─────────────┘                                                          
┌─────────────┴─────────────┐                             
│         HASH_JOIN         │                             
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                             
│           RIGHT           ├──────────────┐              
│           id=id           │              │              
└─────────────┬─────────────┘              │                                           
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│          SEQ_SCAN         ││          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             t2            ││             t1            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            ││             id            │
└───────────────────────────┘└───────────────────────────┘  
```

This is correct from a logical level, but there was a bug in the hash join in dealing with `NULL` keys of RIGHT/FULL outer joins. The hash join would discard all keys with `NULL` because it knew there could not be any matches. This is correct for most join types (inner, left, etc) but is not correct for right and full outer joins, because discarding the keys would lead to no rows being output, when in fact a single row should be output.

Thanks again for the report, nice find :)

**Comment by Mytherin** [comment] 2020-12-01 15:00
This should be fixed now

**Closed by Mytherin** 2020-12-01 15:00 UTC

**Comment by exaatto** [comment] 2020-12-02 08:02
Great job and nice elaboration. I don't even know that duckdb already has such nice explain facility. I can confirm this commit fixes our use case. Again, thanks for making&improving duckdb.

**Comment by vtslab** [comment] 2022-05-24 19:04
Test reopen
