### ISSUE TITLE
NOACCENT.NOCASE comparison with a special character results in a segmentation fault

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#586] opened 2020-04-25 12:35 UTC
Consider the following statements:
```sql
SELECT '' COLLATE NOACCENT.NOCASE='Ʇ';
```
Unexpectedly, the `SELECT` results in a `Segmentation fault` when using a release build. In debug builds, it results in an assertion failure:
```
duckdb_cli: /duckdb/src/common/types/string_type.cpp:14: void duckdb::string_t::Verify(): Assertion `utf_type != UnicodeType::INVALID' failed.
```
I found this based on commit 1d2e40e01de260c9d3306a48c679bebd9a3f8744.

**Comment by Mytherin** [comment] 2020-04-26 10:03
Very impressive find! This was caused by a bug in the `lower` function that did not correctly handle the case where the lower-case character had a different number of bytes than the regular-case character. This resulted in an incorrect UTF-8 string being generated. This is fixed now in 77f3151ecfa85dfa894f3a23feb2271a4cac1ddc.

**Closed** 2020-04-26 19:05 UTC
