### ISSUE TITLE
Support pandas' category type in scans and append

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#569] opened 2020-04-17 09:29 UTC

**Comment by amotl** [comment] 2020-11-27 16:37
Dear Mark and Hannes,

based on a suggestion by @larsrinn to use categorical operations, we are looking into supporting the Pandas `category` type at https://github.com/earthobservations/wetterdienst/issues/226.

When trying to go forward on this, @gutzbenj received:
```
df = duckdb.query(self.df, "data", sql).df()
E       RuntimeError: unsupported python type category
```

I don't know whether there is a chance to improve this as quickly as #959? I don't quite dare to ask.... ;]

With kind regards,
Andreas.

P.S.: Maybe Benjamin will be able to provide a concise MRE like [`pandas_duckdb_test.py`](https://gist.github.com/amotl/a7547aa114f085fa0f96a357190ee493).

**Comment by amotl** [comment] 2020-11-28 19:46
I've just added a concise MRE at [pandas_duckdb_category_unsupported.py](https://gist.github.com/amotl/a7547aa114f085fa0f96a357190ee493#file-pandas_duckdb_category_unsupported-py).

**Comment by Mytherin** [comment] 2020-11-29 13:30
Thanks for the example! Will have a look at implementing this tomorrow.

**Comment by Mytherin** [comment] 2020-12-01 08:33
This should be fixed in the master now, @amotl can you have a look to see if it works as expected?

**Comment by amotl** [comment] 2020-12-01 13:55
Dear Mark,

thank you. Again, that was really quick. I can confirm this does not raise any runtime error anymore.

I believe the fact that DuckDB will not be able to fully roundtrip Pandas data types is by design? Sorry for my naive statement in this regard ;].

So, just for the sake of completeness: When amending [`duckdb_pandas_category.py`](https://gist.github.com/amotl/a7547aa114f085fa0f96a357190ee493#file-duckdb_pandas_category-py) to expect an `int64` type and an `object` type to be returned from the DuckDB query, everything works as expected.

In turn, the in- and out-dataframes will be identical when amending the former one before comparison like
```
df_in["int"] = df_in["int"].astype("int64")
df_in["string"] = df_in["string"].astype("object")
```

I believe this is totally fine. What do you think, @gutzbenj?

Thank you so much again and with kind regards,
Andreas.

**Comment by Mytherin** [comment] 2020-12-01 14:07
No problem! Let me know if you run into any further issues :)

> I believe the fact that DuckDB will not be able to fully roundtrip Pandas data types is by design? Sorry for my naive statement in this regard ;].

DuckDB currently only returns "simple" arrays (i.e. NumPy arrays) when converting back to Python. Perhaps we will return category arrays there in the future, but there is no guarantee the type of the array will be the same as what was put into the system. (i.e. round-trip compatibility is not guaranteed).

Pandas has a weird type system where there is a mix between the logical type (i.e. what is stored in the column, such as integers or strings) and the physical representation of that type (e.g. NumPy array, categorical, etc). DuckDB will maintain the logical type, but not the physical representation.

It would be possible to add other functions such as e.g. `as_category`, that would output a category array instead of a NumPy array for a specific column, but this is then specified by the user when fetching the result, and not related to what was put into the system.

**Comment by amotl** [comment] 2020-12-01 17:53
Thanks for the elaboration on this topic. I recognize being fully roundtrippable wrt. Pandas is not the scope of DuckDB. Adding convenience functions like `as_category` as we go might make sense, but we can well let this be the obligation of the user for a while.

Thanks again for your responsiveness. Cheers!

**Closed** 2021-03-22 11:03 UTC
Labels: Python
