### ISSUE TITLE
Recursive CTEs sql excuted but returned the wrong answer

### ISSUE THREAD

**Issue by rainmaple** [cwida/duckdb#869] opened 2020-08-27 06:56 UTC
We want to figure out how the Recursive CTEs sql excuted in Duckdb, but the duckdb engine return the wrong answer when i tried the example sql refer to the [simple tutorial](https://www.cybertec-postgresql.com/en/recursive-queries-postgresql/), that is to say the recursive process may have some problem in.  I wonder where the bug exists and would be grateful if you can share some tutorials or other useful resources for evaluating and learning about the recursive CTEs in duckdb.

Example sql,  the description of it : "We want to find all the subordinates of person 7566, including the person itself."
while, the duckdb only return the person itself.
```
WITH RECURSIVE ctename AS (
      SELECT empno, ename
      FROM emp
      WHERE empno = 7566
   UNION ALL
      SELECT emp.empno, emp.ename
      FROM emp
         JOIN ctename ON emp.mgr = ctename.empno
)
SELECT * FROM ctename;
```
use the data 
[emp.txt](https://github.com/cwida/duckdb/files/5134491/emp.txt)
you can import the data by rename it into emp.csv then 

`con.Query("COPY emp FROM '"+ data_dir +"emp.csv' WITH DELIMITER '|' CSV HEADER;");`

schema:
```
    con.Query("create table emp ("
              " empno integer not null PRIMARY KEY, "
              "ename varchar, job varchar, mgr integer, "
              "hiredate date, sal double precision, "
              "comm double precision, "
              "deptno integer);");
```

**Comment by Mytherin** [comment] 2020-08-27 08:01
Thanks for opening the issue! It looks like this is a bug in the recursive CTE implementation. I will have a look at fixing it.

**Comment by Alex-Monahan** [comment] 2020-08-29 15:01
I am also having some recursive CTE issues, but I'm still trying to see if it is user error! Results are coming back but don't appear to be complete. It's a huge dataset (70 million rows), so it's taking some time to see if it is a data quality problem, an issue with my SQL,or something in DuckDB.

**Comment by Mytherin** [comment] 2020-08-29 17:33
I had a small look and I think I broke the recursive CTEs when I implemented the query pipelining, so it seems they currently only execute a single iteration if there are more complex operations involved. Will have a look at fixing it.

**Comment by Alex-Monahan** [comment] 2020-08-29 18:23
Is there an older version I can pip install to use the working version in the meantime? Maybe 1.9?

**Comment by Mytherin** [comment] 2020-08-29 18:57
It would be one or two versions back. Not sure about the exact version number.

**Comment by rainmaple** [comment] 2020-08-31 08:25
> Thanks for opening the issue! It looks like this is a bug in the recursive CTE implementation. I will have a look at fixing it.



> I had a small look and I think I broke the recursive CTEs when I implemented the query pipelining, so it seems they currently only execute a single iteration if there are more complex operations involved. Will have a look at fixing it.

Indeed, After debugging the physical plan of RECURSIVE_CTE, i found that duckdb engine only excuted single iteration when visit `PhysicalRecursiveCTE::GetChunkInternal(ExecutionContext &context, DataChunk &chunk,
                                            PhysicalOperatorState *state_)`  method. After the working table being initialized, the size of the chunk fetched by `children[1]->GetChunk(context, chunk, state->bottom_state.get());` is 0;  may be the plan is not complete.

**Comment by kryonix** [comment] 2020-08-31 11:07
```
physical_plan|PROJECTION[empno ename]
REC_CTE
    PROJECTION[empno ename]
        FILTER[empno=7566]
            INDEX_SCAN[emp[NULL]]
    PROJECTION[empno ename]
        HASH_JOIN[INNER mgr=empno]
            SEQ_SCAN[emp]
            CHUNK_SCAN
```

@rainmaple I think the plan looks fine, but the `HASH_JOIN` seems to be problematic. `physical_hash_join.cpp` line 169: `if (sink.hash_table->size() == 0 &&`. This condition is always true for this query. Therefore no rows are returned by the `HASH_JOIN`, and `REC_CTE` is done – as there are no new rows, that's expected behavior.

@Mytherin I think you are right about the query pipelining. It might be an issue of dependencies, maybe? (Not sure about deadlocks though, the dependencies would be cyclic.) The `HASH_JOIN` must not be executed prior to the base case of `REC_CTE`. But I think that's the case. As I briefly mentioned in #404, each operator must be _rescannable/resettable_ after each iteration. That's because the result of `CHUNK_SCAN` changes.
`REC_CTE` uses `state->bottom_state = children[1]->GetOperatorState();` to do so. But apparently this doesn't work in this case.

**Comment by Mytherin** [comment] 2020-08-31 13:13
@kryonix Thanks for looking into it! Indeed the structure of operators has changed since the pipelining was introduced. Fetching a new operator state no longer resets the operators entirely, as the sink state introduced by previous pipelines remains. For correct behavior the pipelines need to be re-run for every iteration; at least the pipelines that depend on the recursive table definition.

I will open a branch to see if I can fix these issues and work on it this week.

**Comment by Mytherin** [comment] 2020-09-03 08:21
Should be fixed now

**Closed by Mytherin** 2020-09-03 08:21 UTC
