### ISSUE TITLE
Not running on Ubuntu 18.04.5 (missing something..?)

### ISSUE THREAD

**Issue by pepa65** [cwida/duckdb#920] opened 2020-09-20 06:43 UTC
Downloaded the Linux CLI binary (0.21, same results with e26286d9823c0b71bd02cf2e184e9031c9a273df):
`file duckdb`:
`ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=dd8544b648321f5918a10ef3808a1f17044c6f19, not stripped`

When running it: `duckdb`:
`duckdb: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by duckdb)`

I have `/usr/lib/x86_64-linux-gnu/libstdc++.so.6` from package `libstdc++6:amd64` , but something is wrong... This is on Ubuntu 18.04.5 LTS.

**Comment by hannesmuehleisen** [comment] 2020-09-20 06:57
We should probably build these on an old Linux to avoid this, apologies. In the meantime, build from source?

**Comment by pepa65** [comment] 2020-09-20 07:09
Build from source (e26286d9823c0b71bd02cf2e184e9031c9a273df) works flawlessly!

**Comment by kamikazechaser** [comment] 2020-09-22 10:54
Yeah this will be an issue. 18.04 is LTS. Derivative OS's like Peppermint will also suffer.

**Comment by pepa65** [comment] 2020-09-22 12:31
Quite a few of those still around... Because it's just a single binary, it's not too hard to provide for these use cases. I'm willing to share mine. :-D

**Comment by mskyttner** [comment] 2020-11-04 20:55
I'm running into this too when attempting to run the v 0.2.2 cli on Ubuntu 18.04.5 LTS, but I wasn't able to find how to install the required system lib (of the correct version). 

There seems to be a removed SO post about this installation issue: https://stackoverflow.com/questions/64490614/duckdb-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-glibcxx-3-4-26-not

After downloading the file www.duckdb.org (cli, binary, linux, 0.2.2) I tried this:

```
roger@mba:~/bin$ duckdb
duckdb: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by duckdb)
```

It seems it is 3.4.25 is there and earlier versions, but not the required version of GLIBCXX_3.4.26:

```
roger@mba:~/bin$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX_3.4.2.
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25

roger@mba:~/bin$ uname -a
Linux mba 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

roger@mba:~/bin$ cat /etc/issue
Ubuntu 18.04.5 LTS \n \l
```

I then tried to see if I could run that file in a Debian container, and created a Dockerfile with this content:

```
FROM debian:stable-slim

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

ADD https://github.com/cwida/duckdb/releases/download/v0.2.2/duckdb_cli-linux-am
d64.zip /duckdb
RUN apt update -y && apt install --no-install-recommends -y unzip && \
	unzip -o duckdb
RUN chmod +x /duckdb

CMD ["/duckdb"]
```
I saved this textfile with the name "Dockerfile" and was able to build it with `docker build -t duckdb .`

Running it, I got the same complaint:

```
roger@mba:~/bin$ docker run -it --rm duckdb
/duckdb: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /duckdb)
```
I also tried the binary on a few other computers, but none of them were enough up-to-date to run it.

Would it be possible to package this file as an selfcontained AppImage file to be provided from the download page in addition to what is there already? 

It would become more portable across a wider set of linuxes and seems to be a good fit or packaging style for a binary of this nature? I guess it adds bytes but it would run out of the box in more places without requiring buildchains etc installed?

https://www.booleanworld.com/creating-linux-apps-run-anywhere-appimage/

**Comment by pepa65** [comment] 2020-11-05 05:03
I was going to share the version that works with Ubuntu 18.04 (GLIBCXX_3.4.25), but then I discovered that it didn't work on my old server (Ubuntu 16.04), so I build that too: [duckdb for GLIBCXX_3.4.22 or higher](https://4e4.win/duckdb_GLIBCXX_3.4.22)

**Comment by mskyttner** [comment] 2020-11-05 14:55
Thanks! With that binary, it runs on stable debian too, tested with this Dockerfile:

```docker
FROM debian:stable-slim

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

#ADD https://github.com/cwida/duckdb/releases/download/v0.2.2/duckdb_cli-linux-amd64.zip /duckdb
#RUN apt update -y && apt install --no-install-recommends -y unzip && \
#	unzip -o duckdb

# use pepa65 build (... should run on Ubuntu 16, 18 too)
ADD https://4e4.win/duckdb_GLIBCXX_3.4.22 /usr/local/bin/duckdb
RUN chmod +x /usr/local/bin/duckdb

WORKDIR /data
VOLUME ["/data"]

CMD ["duckdb --help"]

# README

# to build this image, use "docker build -t cwida/duckdb ."

# to display cli options, use "docker run --rm -it cwida/duckdb" (displays help)

# to run w local db file 'myduckdb.ddb' in present working directory, use:
# docker run --rm -it -v "$(pwd)":"/data" cwida/duckdb duckdb myduckdb.ddb

# the duckdb command ".save myowninmemdb" complains about "sqlite3_backup_init: unsupported"
# so some other lib might be missing or functionality for saving might be WIP?
```

**Comment by pepa65** [comment] 2020-11-05 15:35
Not sure why there is `sqlite3_backup_init: unsupported`. I tried installing `libsqlite3-dev` and rebuilding, but this error is there. Maybe another Issue?

**Comment by Mytherin** [comment] 2020-11-05 16:27
That error is not from SQLite itself, it's from our SQLite3 API wrapper. We wrap the internal SQLite API in order to use the shell. However, since the API has many operations (and many we are not interested in) we have not implemented all of them. When a function that is not implemented gets used we print a warning message and return an error condition. The backup API is one of those cases.

Can you describe the actions you took that leads to this warning being printed? Just starting up the shell on Ubuntu? Does the error prevent you from doing anything else afterwards?

**Comment by pepa65** [comment] 2020-11-05 16:36
It was after a `.save` and after the error printed the prompt came back.

**Comment by Mytherin** [comment] 2020-11-05 16:38
Indeed `.save` is not supported yet, so this is expected behavior currently. Thanks for the report!

**Comment by hannesmuehleisen** [comment] 2020-11-05 18:27
Can you try the latest build from https://github.com/cwida/duckdb/releases/download/master-builds/duckdb_cli-linux-amd64.zip

**Comment by mskyttner** [comment] 2020-11-05 20:02
I tried it but still get the same error message. 

First test was with Ubuntu 18.04.5 LTS, downloading to ~/bin and doing chmod +x then running it.

Second I tested to put it on Debian using a locally reproducible build based on this Dockerfile:

```Dockerfile
FROM debian:stable-slim

# tiny init process reaper to avoid zombie processes 
# (not necessary in later versions of Docker, where it is built in)
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

# install duckdb CLI binary
#ARG DUCK_VER=v0.2.2
#ENV DUCK_CLI https://github.com/cwida/duckdb/releases/download/${DUCK_VER}/duckdb_cli-linux-amd64.zip
ENV DUCK_CLI https://github.com/cwida/duckdb/releases/download/master-builds/duckdb_cli-linux-amd64.zip
WORKDIR /usr/local/bin
ADD ${DUCK_CLI} duckdb.zip
RUN apt-get update -y && apt-get install --no-install-recommends -y unzip && \
	unzip -o duckdb && \
	chmod +x duckdb

WORKDIR /data
VOLUME ["/data"]

CMD ["duckdb --help"]
```

I built that with the command `docker build -t cwida/duckdb .` and running it I got:

```bash
roger@mba:~/repos/duckdb$ docker run --rm -it cwida/duckdb duckdb --help
duckdb: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by duckdb)
```

**Comment by pepa65** [comment] 2020-11-06 00:26
```
duckdb: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found
```
That latest build still requires GLIBCXX_3.4.26.

**Comment by pepa65** [comment] 2020-11-06 08:49
It's weird... The build from master at https://github.com/cwida/duckdb/releases/download/master-builds/duckdb_cli-linux-amd64.zip seems to be looking for either GLIBCXX_3.4.26  on 18.04 (which has GLIBCXX_3.4.25), but the same binary on 14.04 (which has GLIBCXX_3.4.19) is looking for GLIBCXX_3.4.20/21/22/26 (and for CXXABI_1.3.8, while it only has CXXABI_1.3.7). None of them are working.

**Comment by pepa65** [comment] 2020-11-06 10:14
For curiosity's sake I tried building on Ubuntu 14.04 (still supported for over 3 years) and it works, also on all Ubuntu's after it (GLIBCXX_3.4.19 or highter and CXXABI_1.3.7 or higher): [duckdb_cli](https://4e4.win/duckdb)

**Comment by mskyttner** [comment] 2020-11-06 10:40
@pepa65 what is the setting you're making when building to get it to use a lower version of GLIBCXX? 

I'm a bit curious to try this out: https://github.com/AppImageCrafters/build-appimage-action, although I don't have much experience from building AppImages. But then the build steps you're taking would be nice to have.

**Comment by pepa65** [comment] 2020-11-06 11:25
Just install/bootup a more ancient Linux, make sure cmake3 and python3 (and other build-essentials) are installed, and then just get the latest source from duckdb, and do `make` in the source's root directory. It's described in the README, it's very simple, and seems to work really well.

**Comment by mskyttner** [comment] 2020-11-07 19:32
Thanks @pepa65 for the info. With this multistage Dockerfile the build of duckdb CLI tool worked out fine and gave a binary that I could run on Debian and Ubuntu 18. The build didn't require python3 to be installed:

```Dockerfile
FROM ubuntu:trusty

RUN apt-get update -y && apt-get install -y \
	unzip \
	ninja-build \
	build-essential \
	cmake3 \
	curl

WORKDIR /build

RUN curl -fL https://github.com/cwida/duckdb/archive/v0.2.2.tar.gz -o duckdb.tgz && \
	tar xfz duckdb.tgz --strip-components=1 && \
	rm duckdb.tgz

RUN cmake . -G Ninja
RUN ninja -j 3

FROM debian:stable-slim

WORKDIR /usr/local/bin
COPY --from=0 /build/duckdb .
RUN chmod +x duckdb

WORKDIR /data
VOLUME ["/data"]

CMD ["duckdb --help"]

```

I copied out the binary (using "docker cp") from the image and it ran locally on the host, just like the one you provided. 

Perhaps into wouldn't run directly on a Raspberry Pi, but the "docker buildx" command with the above Dockerfile might be used to fix that:

```bash
# use docker and "buildx" cli plugin, to build for linux/arm64:
# see https://github.com/docker/buildx
docker run --privileged --rm tonistiigi/binfmt --install all
export DOCKER_CLI_EXPERIMENTAL=enabled
docker buildx build -t cwida/duckdb --platform=linux/arm64 .
```

I think the AppImage packaging wouldn't be completely pointless, if I understood it correctly, since it would bundle all the necessary stuff into a single executable file, therefore making it more portable, without requiring a particular system library of some version already being installed on the host (while baking that in makes it less tiny though).

**Comment by pepa65** [comment] 2020-11-08 06:34
It would be nice if there were static binaries available for each platform, so they would always run! (Which is what AppImage binaries are, but since the application itself is already a single binary, maybe some way of compiling all dependencies into a single static binary would be possible.)

If python3 really isn't required for building, it shouldn't be listed in `README.md`.

**Comment by rongfengliang** [comment] 2020-11-09 08:33
@pepa65  copy  new ibstdc++ library && add softlink  maybe help  https://github.com/rongfengliang/libstdc-so

**Comment by pepa65** [comment] 2020-11-09 11:51
Thanks for making those! Do they just work with the rest of my environment & applications from the repos? Of course it leads to a conflict with the repository managing software, to replace `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`...

**Comment by rongfengliang** [comment] 2020-11-10 00:42
> Thanks for making those! Do they just work with the rest of my environment & applications from the repos? Of course it leads to a conflict with the repository managing software, to replace `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`... 

yes this way maybe cause conflict,with static library maybe better

**Comment by mskyttner** [comment] 2020-11-17 19:11
I tried out making a build of an [AppImage](https://appimage.org/) packaging of the duckdb CLI, which seems to run on my Mint and Ubuntu boxes (which are not exactly bleeding edge). It is a cloud build using [this workflow](https://github.com/mskyttner/duckdb-cli-builds/blob/main/.github/workflows/push-duckdb-cli-appimage.yml). 

It provides a single file of 11MB which includes everything needed to run it. It is available [here](https://github.com/mskyttner/duckdb-cli-builds/releases/download/refs%2Fheads%2Fmain/duckdb-x86_64.AppImage)

@rongfengliang @pepa65 if you download this one, and try it out does it run for you too?

```bash
wget "https://github.com/mskyttner/duckdb-cli-builds/releases/download/refs%2Fheads%2Fmain/duckdb-x86_64.AppImage"
chmod +x duckdb-x86_64.AppImage
./duckdb-x86_64.AppImage

#file duckdb-x86_64.AppImage 
#duckdb-x86_64.AppImage: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, stripped
```

**Comment by pepa65** [comment] 2020-11-17 23:43
That seems to work well, and for all it includes is one third of the size of just the built binary..!

**Comment by hannesmuehleisen** [comment] 2020-11-19 07:51
Could you try the latest binary from https://github.com/cwida/duckdb/releases/download/master-builds/duckdb_cli-linux-amd64.zip ?

**Comment by pepa65** [comment] 2020-11-19 07:58
Yes, this works on 18.04 and 16.04 (haven't tried 14.04 yet).

**Comment by hannesmuehleisen** [comment] 2020-11-19 08:33
Excellent. I propose to close this issue then.

**Closed** 2020-11-19 08:35 UTC

**Comment by qiuwei** [comment] 2021-01-02 10:19
The java package has exactly the same problem on ubuntu 18.04

**Comment by hannesmuehleisen** [comment] 2021-01-02 15:55
> The java package has exactly the same problem on ubuntu 18.04

Could you be more specific please? Which OS/Java versions etc?
