### ISSUE TITLE
Binder Error: column xxxx must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by phillc73** [cwida/duckdb#1358] opened 2021-02-02 18:47 UTC
Was trying to compare `duckdb` with the [tidyquery](https://github.com/ianmcook/tidyquery) library for R. Using the example SQL query from the `tidyquery` page I'm running into the following error with `duckdb`:

`
Error: Binder Error: column num_flts must appear in the GROUP BY clause or be used in an aggregate function
`

Works fine with `tidyquery`

Code to reproduce:

```r
library(duckdb)
library(tidyquery)
library(nycflights13)

tidyquery::query(
"SELECT origin, dest,
    COUNT(flight) AS num_flts,
    round(SUM(seats)) AS num_seats,
    round(AVG(arr_delay)) AS avg_delay
  FROM flights f LEFT OUTER JOIN planes p
    ON f.tailnum = p.tailnum
  WHERE distance BETWEEN 200 AND 300
    AND air_time IS NOT NULL
  GROUP BY origin, dest
  HAVING num_flts > 3000
  ORDER BY num_seats DESC, avg_delay ASC
  LIMIT 2;"
)

A tibble: 2 x 5
  origin dest  num_flts num_seats avg_delay
  <chr>  <chr>    <int>     <dbl>     <dbl>
1 LGA    DCA       4468    712643         6
2 EWR    BOS       5247    611192         5

con <- DBI::dbConnect(duckdb::duckdb(), ":memory:", read_only = FALSE)

# register a dataframe view in duckdb
duckdb::duckdb_register(con, "flights", flights)
duckdb::duckdb_register(con, "planes", planes)

# execute required SQL query against the new DuckDB table views
statement_result <- DBI::dbGetQuery(con,
"SELECT origin, dest,
    COUNT(flight) AS num_flts,
    round(SUM(seats)) AS num_seats,
    round(AVG(arr_delay)) AS avg_delay
  FROM flights f LEFT OUTER JOIN planes p
    ON f.tailnum = p.tailnum
  WHERE distance BETWEEN 200 AND 300
    AND air_time IS NOT NULL
  GROUP BY origin, dest
  HAVING num_flts > 3000
  ORDER BY num_seats DESC, avg_delay ASC
  LIMIT 2;"
)

# close the connection
DBI::dbDisconnect(con, shutdown = TRUE)

Error in .local(conn, statement, ...) : 
  duckdb_prepare_R: Failed to prepare query SELECT origin, dest,
    COUNT(flight) AS num_flts,
    round(SUM(seats)) AS num_seats,
    round(AVG(arr_delay)) AS avg_delay
  FROM flights f LEFT OUTER JOIN planes p
    ON f.tailnum = p.tailnum
  WHERE distance BETWEEN 200 AND 300
    AND air_time IS NOT NULL
  GROUP BY origin, dest
  HAVING num_flts > 3000
  ORDER BY num_seats DESC, avg_delay ASC
  LIMIT 2;
Error: Binder Error: column num_flts must appear in the GROUP BY clause or be used in an aggregate function
```

`sessionInfo()`

R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyquery_0.2.1    nycflights13_1.0.1 duckdb_0.2.3       DBI_1.1.1         

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        lubridate_1.7.9.2 fansi_0.4.2       utf8_1.1.4        assertthat_0.2.1  crayon_1.3.4      dplyr_1.0.3       R6_2.5.0          lifecycle_0.2.0   magrittr_2.0.1   
[11] pillar_1.4.7      cli_2.2.0         stringi_1.5.3     rlang_0.4.10      vctrs_0.3.6       generics_0.1.0    ellipsis_0.3.1    tools_4.0.3       stringr_1.4.0     glue_1.4.2       
[21] purrr_0.3.4       compiler_4.0.3    pkgconfig_2.0.3   queryparser_0.3.1 tidyselect_1.1.0  tibble_3.0.5

**Comment by Mytherin** [comment] 2021-02-03 07:47
Thanks for the report! I can confirm this is a bug with using an alias to an aggregate in the `HAVING` clause. I will have a look at fixing it.

As a work-around, you could directly use the aggregate in the HAVING clause for now, i.e.:

```sql
SELECT origin, dest,
    COUNT(flight) AS num_flts,
    round(SUM(seats)) AS num_seats,
    round(AVG(arr_delay)) AS avg_delay
  FROM flights f LEFT OUTER JOIN planes p
    ON f.tailnum = p.tailnum
  WHERE distance BETWEEN 200 AND 300
    AND air_time IS NOT NULL
  GROUP BY origin, dest
  HAVING COUNT(flight) > 3000
  ORDER BY num_seats DESC, avg_delay ASC
  LIMIT 2;
```

**Comment by Mytherin** [comment] 2021-02-03 19:48
This should be fixed now in the master branch. Thanks again for the report!

**Closed by Mytherin** 2021-02-03 19:48 UTC

**Comment by phillc73** [comment] 2021-02-10 09:52
Perhaps of interest, I ran this complex SQL query, with the small change to work with `duckdb v0.2.4` using the `duckdf` library, comparing the timed results to both `tidyquery` and `dplyr`. Turns out the `duckdb` with `duckdf` combination was quickest.

Benchmarks at the bottom of this [README](https://github.com/phillc73/duckdf).

**Comment by sahoosatish** [comment] 2022-07-17 16:03
Hi, I see that this thread is closed and it says its already fixed in duckdb. But I still get the same error with the following query-
%%sql
select *,min(tarfyear) as tarfyearmin from
(select a.*,b.fyear as tarfyear from
comp a left join comp b
on a.gvkey=b.gvkey and a.fyear<=b.fyear and b.impd=1)
group by gvkey,fyear having tarfyear=min(tarfyear)

I get the error "Binder Error: column unnamed_subquery7.tarfyear must appear in the GROUP BY clause or be used in an aggregate function" 
I have tried using both  having tarfyear=min(tarfyear) and  having tarfyear=tarfyearmin 
Both give the same error.

I am using duckdb as the backend in python to use SQL on pandas. I am assuming the fix is at duckdb level and hence should apply to python usage as well. But I still see the same error.
Please advise.
Thanks

**Comment by Mause** [comment] 2022-07-17 16:37
@sahoosatish can you please create a new issue with all the relevant version information?

**Comment by Alex-Monahan** [comment] 2022-07-17 16:41
@sahoosatish , could you also prefix your code with a new line with just \`\`\`sql, then end it with a new line of just ```. I think an asterisk is missing since it was interpreted as markdown in some way.
