### ISSUE TITLE
pip install is not working

### ISSUE THREAD

**Issue by xhochy** [cwida/duckdb#227] opened 2019-06-30 19:25 UTC
Newer versions of `pip` run `python setup.py bdist_wheel` in a temporary folder and then install the wheel into the environment. This fails as only the `pythonpkg` folder is copied over and not the remaining C++ sources.

**Comment by hannesmuehleisen** [comment] 2019-09-24 16:30
I just tried this with the latest pip (19.2.3) and could not reproduce the issue like so:
`pip3 install -e tools/pythonpkg`
Could you perhaps tell me how to provoke this issue?

**Comment by arjenpdevries** [comment] 2019-12-30 12:28
The @hannesmuehleisen instruction works for me too, but there is a catch:
the files installed include only package metadata, and the actual source files used remain where they are; which is fine in development mode.

However, I was trying to install a self-compiled DuckDB and the Python package in a Google Cloud Platform storage bucket mounted from a Colab notebook, using an install with `--prefix` pointing to the storage bucket. In that case, the real code (still in the checked out repo) is "lost" when Colab shuts down (and all files local to the notebook are gone).

In this scenario, the Python package needs to be installed by first copying the files from `tools/pythonpkg` to the storage bucket, and subsequently running `pip3 install -e` from that directory.

Note that this *still* causes a minor problem: `get_version()` does not work if the sources are not in `../..`; I suspect that this is similar to the issue that @xhochy refers to - assuming that `conda` does also need to move the package files around (I am not sure). 

I am sending a pull request now that helps overcome this issue:
https://github.com/cwida/duckdb/pull/381

**Comment by hannesmuehleisen** [comment] 2020-03-03 11:33
We changed the python module to use the amalgamation by default, could you see whether this fixes the issue?

**Comment by arjenpdevries** [comment] 2020-03-11 12:25
It does not fix it, unfortunately. Using `pip3 -vvv` I noticed a hint that may help understand the root of the problem eventually: 

```
[arjen@apc duckdb]$  pip3 -vvv uninstall duckdb
Found existing installation: duckdb 0.1.3.dev309+g800d009e
Not sure how to uninstall: duckdb 0.1.3.dev309+g800d009e - Check: /home/arjen/gh/duckdb/tools/pythonpkg
Can't uninstall 'duckdb'. No files were found to uninstall.
```
Looks like the uninstall option is looking for a file that does not exist if the package is installed with a `--prefix` parameter.

Validated by installing without prefix, and then uninstalling - that works fine.
I think it looks for `duckdb.egg-link` in the wrong place.

**Comment by arjenpdevries** [comment] 2020-03-11 12:28
If you `install` the package twice:
1. install with prefix
2. install without prefix

You can also `uninstall` twice.

The first time, all fine:
```
[arjen@apc duckdb]$  pip3 -v uninstall duckdb 
Found existing installation: duckdb 0.1.3.dev309+g800d009e
Uninstalling duckdb-0.1.3.dev309+g800d009e:
  Would remove:
    /home/arjen/.local/lib/python3.7/site-packages/duckdb.egg-link
  Will actually move:
    /home/arjen/.local/lib/python3.7/site-packages/duckdb.egg-link
Proceed (y/n)? y
  Created temporary directory: /tmp/pip-uninstall-8tnnqd9_
  Removing file or directory /home/arjen/.local/lib/python3.7/site-packages/duckdb.egg-link
  Removing pth entries from /home/arjen/.local/lib/python3.7/site-packages/easy-install.pth:
  Removing entry: /home/arjen/gh/duckdb/tools/pythonpkg
  Successfully uninstalled duckdb-0.1.3.dev309+g800d009e
```

The second time:
```
[arjen@apc duckdb]$  pip3 -v uninstall duckdb 
Found existing installation: duckdb 0.1.3.dev309+g800d009e
Not sure how to uninstall: duckdb 0.1.3.dev309+g800d009e - Check: /home/arjen/gh/duckdb/tools/pythonpkg
Can't uninstall 'duckdb'. No files were found to uninstall.
```

Now if I only knew how `pip` checks for the installed version!

**Comment by hannesmuehleisen** [comment] 2020-03-11 12:41
@arjenpdevries would you agree that this looks more like a pip issue?

**Comment by arjenpdevries** [comment] 2020-03-11 12:44
Actually, yes, after digging a bit deeper, it seems to be pip. Although ppl claim it is fixed for a modern pip, I have not encountered one. Could be that we have wrong metadata, unsure - but uninstalling packages installed with `-e` is definitely a problem-rich setting. Feel free to close the issue.

**Comment by arjenpdevries** [comment] 2020-03-11 12:46
Just for the record:
https://stackoverflow.com/questions/17346619/how-to-uninstall-editable-packages-with-pip-installed-with-e

**Closed** 2020-03-11 14:04 UTC
Labels: Python
