### ISSUE TITLE
Using the INTERVAL type

### ISSUE THREAD

**Issue by zenazn** [cwida/duckdb#1426] opened 2021-02-22 00:53 UTC
One use case I'm trying to use duckdb for is to determine how many days have elapsed between two dates. The way I thought to do this was to first calculate `end_date - start_date`, but this leaves me with an INTERVAL type. Unfortunately, there do not appear to be any functions that act on INTERVAL types (I looked [here](https://duckdb.org/docs/sql/functions/date), and searched the codebase for functions on `interval_t`), and I wasn't able to cast an interval to a numeric type.

In Postgres, [`date_part` / `extract` work on the interval type](https://www.postgresql.org/docs/11/functions-datetime.html). I would be able to write `date_part('day', end_date - start_date)`.

Is this something you'd be willing to add to duckdb? I briefly looked into implementing it, but I'm not familiar enough with C++ and DuckDB's dispatch to immediately know how to approach it. With a little bit of guidance I'd be willing to contribute a patch, though!

**Comment by zenazn** [comment] 2021-02-22 01:01
As a workaround for INTERVALs up to a year, I've done this:

```sql
select date_part('day', (date '1999-12-31') + (end_date - start_date)) as diff_in_days
```

**Comment by Mytherin** [comment] 2021-02-22 09:06
Thanks for opening the issue. For sure this is something we want to add to DuckDB! Only we have not gotten to it yet. You can have a look at our [date part implementation here](https://github.com/cwida/duckdb/blob/78eab23778b76b2ce4d0645d3125eb3d080d1846/src/function/scalar/date/date_part.cpp) if you want to have a go at it. Feel free to ask any questions here. Otherwise we will likely pick this up ourselves later on :)

**Comment by hawkfish** [comment] 2021-02-22 17:01
It looks like the issue is just that the `date_part` code only handles `date` types and not `interval` types.  I can have a look at this as dates are one of my things, but I don't know how tasks like this get assigned to prevent overlap?

**Comment by Mytherin** [comment] 2021-02-22 17:02
Like this :) thanks!

**Comment by hawkfish** [comment] 2021-02-22 23:36
This goes for `DATE`s too:

> The `extract` function retrieves subfields such as year or hour from date/time values. **_source_** must be a value expression of type `timestamp`, `time`, or `interval`. (Expressions of type `date` are cast to `timestamp` and can therefore be used as well.)

**Comment by hawkfish** [comment] 2021-02-23 23:09
One problem is that `time_t` appears to be an identical type to one of the other temporal types, making templatised compilations rather difficult...

**Comment by hannesmuehleisen** [comment] 2021-02-24 08:20
`dtime_t` is the correct type for DuckDB time, it has bitten me before as well

**Comment by hawkfish** [comment] 2021-02-24 23:25
I wrapped it in a `struct`. If that is what you did, we should think about making this generally available.  Especially if the `struct` has cast operators to the underlying type?

**Comment by hawkfish** [comment] 2021-02-27 16:25
I think this is done now?

**Comment by Alex-Monahan** [comment] 2021-02-27 16:33
Would it be possible to map the Pandas interval data type to DuckDB's interval?

**Comment by hawkfish** [comment] 2021-02-27 16:40
I don't think so. I'm not familiar with `pandas` but it looks like [`pandas.Interval`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Interval.html) is a range type for a scalar domain. The SQL `INTERVAL` type is a (temporal bin reference)[https://github.com/cwida/duckdb/blob/master/src/include/duckdb/common/types.hpp] that counts months, days and microseconds and expresses a _relative_ change in a temporal field with respect to a calendar (Gregorian at the moment.)

**Comment by Alex-Monahan** [comment] 2021-02-27 16:52
You are correct, my mistake! Maybe the time delta type is what I was thinking of?

It's not a high priority, just something that would be nice for Pandas interoperability. I don't have a concrete use for it today.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timedelta.html

**Comment by Alex-Monahan** [comment] 2021-02-27 16:54
Confusingly, there is a numpy time delta type, and it looks like the interval type might support an interval of date times.
https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#basics-dtypes

**Comment by hawkfish** [comment] 2021-02-27 16:59
Both of these types model a single bin (e.g., months) so we could certainly import from these types to the DuckDB `INTERVAL` type. The reverse mapping would not be possible because `INTERVAL` models multiple bins. 

This all seems like a separate issue, so please feel free to submit it.

**Comment by hawkfish** [comment] 2021-03-03 16:06
I've updated the documentation. Can we close this now?

**Closed** 2021-03-04 08:39 UTC

**Comment by zenazn** [comment] 2021-03-04 20:57
Thank you, all! This will be really helpful for us :)
