### ISSUE TITLE
Failure to import CSV using CLI

### ISSUE THREAD

**Issue by mrayva** [cwida/duckdb#811] opened 2020-08-05 15:46 UTC
sqlite> SELECT * FROM read_csv_auto('import\TEST.csv');
Error: Not implemented: Unimplemented type for cast (VARCHAR -> NULL)

TEST.csv was produced by jq ( I cannot attach it since the data is proprietary )

Narrowed it down to 46901  line of the file, but , clearly, the line content is not the issue..it imports fine by itself.

Why no line number is printed out on failure?

**Comment by Mytherin** [comment] 2020-08-05 16:29
Thanks for the bug report! Indeed a line number should be printed out for any CSV errors. The reason it seems to not do that in this case is because this is an internal error rather than a regular CSV reader error. It seems to be related to the CSV Auto selecting the SQLNULL field for a column (with perhaps empty values?), which is generally not a valid type.

Can you confirm that using the `COPY` statement where you specify the types yourself works correctly? i.e. first creating the table and then using `COPY tbl FROM 'test.csv' (DELIMITER..)` (see [here](https://duckdb.org/docs/sql/statements/copy) for more docs).

**Comment by tdoehmen** [comment] 2020-08-05 16:42
Thanks for the report. I will try to reproduce the issue with an empty column and fix it in case it creates this issue. Otherwise, it would be helpful to have a sample file that reproduces the issue.

**Comment by tdoehmen** [comment] 2020-08-05 17:00
Update: Managed to reproduce this. I would agree with @Mytherin that it is probably an almost empty column. The type sniffer (which samples values from the column) misses the non-empty values and then the parser chokes on them later on. More on the current behavior and a workaround is explained here: [https://stackoverflow.com/questions/63235906/csv-reader-behavior](https://stackoverflow.com/questions/63235906/csv-reader-behavior). I guess the way forward would be to implement the therein proposed improvements. 
[issue_811.zip](https://github.com/cwida/duckdb/files/5029948/issue_811.zip)

**Comment by Mytherin** [comment] 2020-08-05 17:04
Revising the guess is a bit problematic in the current streaming setup. I would say to resolve this issue we can simply upcast SQLNULL to VARCHAR if the column is almost empty (and there are no expected column types). That should resolve this issue at least.

**Comment by tdoehmen** [comment] 2020-08-05 17:09
We can do that. But it will not be a solution for the related issue of having, say, a numeric column with few string values (as in the linked stackoverflow issue).

**Comment by mrayva** [comment] 2020-08-05 17:31
Yes, there are few columns that all 'blanks' in all rows. Ex) (excerpt)  "USA_CAN","","","","","","-1".
In fact, running BurntSushi's
xsv stats import\TEST.csv

would report these columns as 
Ex)
STOCKID,NULL,,,,0,0,,

Still, I do expect duckdb importer not to catastrophically fail, but import it as <blank> VARCHAR

**Comment by Mytherin** [comment] 2020-08-05 17:45
> We could do that. But if we fix this I think it would be great to fix related issues in one go. E.g. the one of having a numeric column with few string values (as reported in the linked stackoverflow issue). I had a more generic recovery-strategy in mind, which basically catches the error and asks the user to either define the schema by hand, increase the sample size, or run a full scan of the data.

A possible solution would be for the read_csv_auto to take a sampling strategy as input, which defaults to 'sample' (i.e. the current solution). We can then create a second sampling strategy 'complete' or 'full' or so, that actually does a full read of the CSV file and upcasts types as required. Any type error can then be solved by the user switching to 'full' sampling mode, at the expense of a (much) more costly sampling phase. 

> Still, I do expect duckdb importer not to catastrophically fail, but import it as VARCHAR

Agreed, this is a bug that should be fixed. I would say catastrophic failure is reserved for crashing the system though :)

**Comment by mrayva** [comment] 2020-08-05 17:58
I agree - failure was not 'catastrophic' :)   ..but it exited without any attempt of recovery and/or proceeding to the next/'good' rows.
On the other hand, asking a user to 'define the schema by hand' would significantly reduce usability of the import.  Parameter to specify sample size seems to be the way to go...

**Comment by Mytherin** [comment] 2020-08-05 18:41
I agree that defining the schema by hand should be a last-effort and ideally never required. Unfortunately CSV reading is quite a complex problem, and there are many edge cases that make it hard to get right. So thanks for reporting one to us :)

Skipping bad rows is something that sounds good but is often not desirable as well. It could be an option, but I would turn that behaviour off by default as removing data from the CSV file can lead to more difficult to debug problems later on.

Indeed having the user specify the sample size seems to be a better option.

**Comment by Alex-Monahan** [comment] 2020-08-05 18:46
If that sample size could be a percentage between 0 and 1, or a row count, that would be ideal! In our use case, we could write some Python to pull the csv file size, and then make sure that ~10,000 rows got checked by scaling that sample size.

**Comment by tdoehmen** [comment] 2020-08-06 08:58
Adding an option to adapt the sampling strategy should be quite straight forward to implement and I will give it a try in the next days.

**Comment by avo15** [comment] 2020-08-09 23:25
The most durable solution would be to add one more parameter to read table description from additional file supplied with data file. Would be great to have it in both Duckdb and Monetdb

**Comment by Mytherin** [comment] 2020-08-10 06:15
> The most durable solution would be to add one more parameter to read table description from additional file supplied with data file. Would be great to have it in both Duckdb and Monetdb

The table description can already be supplied by first using a `CREATE TABLE` statement and then using the `COPY .. FROM` to load the CSV. Alternatively, the `read_csv` method can take the table statement as a struct, e.g. if you want to load a CSV from a file with two integer columns separated by a comma, you can use the following statement:

```sql
CREATE TABLE integers AS SELECT * FROM read_csv('integers.csv', ',', STRUCT_PACK(i := 'INTEGER', j := 'INTEGER'))
```

The COPY alternative would look like this:
```sql
CREATE TABLE integers(i INTEGER, j INTEGER);
COPY integers FROM 'integers.csv'
```

More documentation about that can be found [here](https://duckdb.org/docs/sql/statements/copy).

**Comment by tdoehmen** [comment] 2020-08-14 10:02
With PR https://github.com/cwida/duckdb/pull/832 we added the option to increase the sample size for dialect and type detection. You can now increase the size and number of samples when the default setting (10 x 100 lines) does not lead to a successful type detection. Also, we added more accurate line number information for failures. Please have a look at the PR for usage examples.

@mrayva, you could now try doing something like this:
`SELECT * FROM read_csv_auto('import\TEST.csv', SAMPLE_SIZE=1024, NUM_SAMPLES=20);`

**Closed** 2020-09-10 14:39 UTC
