### ISSUE TITLE
R devtools package installation requires `build = FALSE` setting

### ISSUE THREAD

**Issue by cboettig** [cwida/duckdb#189] opened 2019-05-17 20:54 UTC
Installation of the package directly from GitHub works fine if we skip the build option:

```r
remotes::install_github("cwida/duckdb/tools/rpkg", build = FALSE)
```

However, the default for `install_github()` is `build = TRUE`.  This also makes it harder to include this package on TravisCI checks since the standard mechanism of adding the package to the `Remotes` field of the DESCRIPTION will first try and build the package.  

The reason for the build failure isn't entirely clear to me, seems to have to do with tmp directories, e.g. see [example travis log](https://travis-ci.org/cboettig/taxadb/builds/533985275#L962-L978).

**Comment by hannesmuehleisen** [comment] 2019-05-19 08:04
confirmed, will have to investigate what's going on there. `remotes` seems to be doing something special there.

**Comment by hannesmuehleisen** [comment] 2019-05-29 12:55
For now there is not a lot I can do to fix this, we need to reshape the source tree to build the tarball properly. I guess it's down to documenting this properly, great that there is a workaround.

**Comment by hannesmuehleisen** [comment] 2019-10-07 15:23
So TIL that `install.packages()` also supports installation from a URL with a tarball directly. So the following works now: 
````R
install.packages("http://download.duckdb.org/rev/b551a19663e8e09446fc765478b9ed8c96c08f69/rstats/duckdb_0.1.0.tar.gz", repos=NULL)
````
for the `master` branch. We could create some aliases so the URL is more constant. Would this be a viable alternative?

**Comment by jessekps** [comment] 2020-01-10 13:58
Neither works for me I'm afraid. I use R 3.6.1 for windows. 

`remotes::install_github("cwida/duckdb/tools/rpkg", build = FALSE)` 

gives the error

`
include_ -DNDEBUG       -I.   -O2 -Wall  -mtune=generic -c duckdbr.cpp -o duckdbr.oduckdbr.cpp_1_22_ fatal error_ duckdb.hpp_ No such file or directory_
`

Indeed there is no duckdb.hpp file in tools/rpkg. So I suppose that I need to run a manual installation of duckdb first? From the tutorial on  https://www.duckdb.org/docs/current/tutorials/installation it seems that I should not have to do that.

**Comment by hannesmuehleisen** [comment] 2020-01-14 08:26
@jessekps can you try 
`install.packages("http://download.duckdb.org/rev/6fcb5ef8e91dcb3c9b2c4ca86dab3b1037446b24/rstats/duckdb_0.1.1.tar.gz", repos=NULL)`

**Comment by jessekps** [comment] 2020-01-14 08:58
That works, thanks! Installation worked with some cpp warnings and the examples run fine.

**Comment by hannesmuehleisen** [comment] 2020-01-14 09:13
Okay, great. We will have to adapt the instructions I think.

**Comment by hannesmuehleisen** [comment] 2020-01-21 10:45
So what we could do is host our own CRAN-like repo, so DuckDB could be installed like so:

`install.packages("duckdb", repos=c("http://download.duckdb.org/r_repo", "http://cran.rstudio.com"))`

This should work with the current revision for now, let me know if this works for you?

**Comment by hannesmuehleisen** [comment] 2020-01-21 10:46
See #392

**Comment by jimhester** [comment] 2020-02-05 14:25
FWIW remotes is not doing anything *special*, it is just building the tarball before installing. 

`R CMD build . && R CMD INSTALL *tar.gz` fails in the exact same way.

**Comment by hannesmuehleisen** [comment] 2020-03-02 13:23
We now recommend to install the R package like so, at least until we are on CRAN:
`install.packages("duckdb", repos=c("http://download.duckdb.org/alias/master/rstats/", "http://cran.rstudio.com"))`

**Comment by hannesmuehleisen** [comment] 2020-03-03 07:34
Closing this for now as devtools is no longer the recommended route and there is not really anything we can do to address this.

**Closed** 2020-03-03 07:34 UTC
Labels: R
