### ISSUE TITLE
Better subquery rewriting

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#64] opened 2018-12-06 07:25 UTC
Not all subqueries get flattened properly, perhaps see this paper:

http://www.btw-2015.de/res/proceedings/Hauptband/Wiss/Neumann-Unnesting_Arbitrary_Querie.pdf

**Comment by hannesmuehleisen** [comment] 2019-02-04 14:38
this is duplicate of #81

**Closed by hannesmuehleisen** 2019-02-04 14:38 UTC
Labels: Optimizer
