### ISSUE TITLE
Large argument to RPAD results in std::bad_alloc

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#610] opened 2020-05-01 21:27 UTC
Consider the following statement:

```sql
SELECT RPAD('a', 100000000000000000, 0); -- Error: std::bad_alloc
```
The `SELECT` results in an error `std::bad_alloc`, after running for a while. Is this expected? I checked with MySQL, which seems to immediately return `NULL` for an overly large size argument.

I found this based on commit 11e51619d8402c649cdb45011944a1ca504060f9.

**Comment by Mytherin** [comment] 2020-05-01 21:39
Interesting! I tried it in MySQL and the limit seems to be `16777216`. 
```sql
SELECT LENGTH(RPAD('a', 16777216, 0));
-- 16777216
SELECT LENGTH(RPAD('a', 16777217, 0));
-- NULL
```

Looking at the MySQL source code this value seems to occur in a bunch of places, this seems to be a likely culprit:

```cpp
#define MAX_BLOB_WIDTH 16777216 /**< Default width for blob */
```

But then, strangely, this does work:
```sql
SELECT LENGTH(CONCAT(RPAD('a', 16777216, 0), RPAD('a', 16777216, 0)));
-- 33554432
```

In this case I think rpad should return an error, though, as the maximum string size our system can handle is 2^31. I think the second argument should be of type INTEGER, instead of of type BIGINT, that should solve the issue. A bad_alloc can still potentially occur if the user doesn't have 2GB of memory, but that is then the expected behavior.

**Comment by hawkfish** [comment] 2020-05-01 22:10
Yes, assign it to me.

**Closed** 2020-05-02 07:36 UTC
