### ISSUE TITLE
Discussion: CRAN release automation 

### ISSUE THREAD

**Issue by pat-s** [cwida/duckdb#798] opened 2020-07-31 10:11 UTC
The plan is to fully automate this via {fledge}.

While {fledge} already does a good job within the various stages of a release process (pre-release/release/post-release) an automation via Travis is somewhat problematic due to the following reasons:

- We would need to enable a CRON job for the release branch. This is not possible programmatically unfortunately (still an open FR in the travis CLI)
- Enabling CRON manually via the web interface is tedious, then we can call the individual stages also manually.

## Suggestion: GitHub Actions

GitHub Actions allows to trigger CRON builds via [tag wildcards](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-branches-and-tags). Here, we could add a dedicated YAML which only triggers a build for `vx.x.x` tag builds.

These builds could run on pushes to branches with the CRAN release pattern (e.g. `r-release-vx.x.x`) and on a periodic basis. The latter is useful when the package is submitted to CRAN to automatically detect CRAN acceptance.

## Workflow

The current workflow would look as follows:

1. When a tag build is detected, `fledge::pre_release()` is executed which creates a new release branch. Artifacts (`cran-comments.md` and others) are written and additional checks are executed.
We could try to detect `rhub` and `winbuilder` failures automatically, however the rate of false-positives is quite high. How do we want to deal with this?
1. After the checks have passed, the boxes in `cran-comments.md` need to be checked (automatically?) and `fledge::release()` is called. This will upload the package to CRAN. There is one manual step in this stage: Copying the URL to upload to CRAN from the email.
One idea could be to forward all CRAN emails to a dummy email account and scrape these via the {gmailr} package.
1. After acceptance, `fledge::post_release()` switches the package version to a development version again and opens a PR to merge the changes.

All of this is done via the macro function `fledge::unleash()` (which still needs to be implemented) which wraps the mentioned child functions.

Currently there are still two open points that need to be implemented/discussed:

- [ ] `release()`: Forward CRAN upload mail and scrape the URL automatically?

- [ ] `pre_release()`: Check whether all tests passed automatically and trigger the release stage

@hannesmuehleisen @krlmlr

**Comment by krlmlr** [comment] 2020-07-31 13:46
I'd like to decouple the discussion:

1. How we achieve automation for the CRAN release
1. What CI system we use

AFAICT the problem is that we can't enable cron by branch pattern, we need to specify an existing branch and can do this only via the web UI. Also, it seems we only need cron to detect when a package has been released to CRAN.

I propose to try the first CRAN release with Travis and see if the problems are worth employing a second CI solution. If we stick to Travis, we can use a hard-coded branch name. Alternatively, we set up a hard-coded branch that bumps any existing `cran-*` branch.

Regarding the workflow:

1. Checking the boxes based on r-hub and winbuilder results and committing the results would be the maintainer's job, at least for now.
1. Clicking the link and checking the buttons would be the maintainer's job too.
1. I think a pull request should be opened at step one -- `fledge::pre_release()` already switches the main branch to the development version after the CRAN release. Upon acceptance on CRAN, the PR could be merged, this could trigger a CI run that performs the tagging.

**Comment by pat-s** [comment] 2020-07-31 16:16
> we need to specify an existing branch and can do this only via the web UI

Ah yes that's odd. Also on GHA CRON builds run only on the master branch for now. So my idea of creating GHA YAML files dynamically within a CI run also won't work (for now).

Let's focus on 1), you are right. This should work in a CI-agnostic way anyway.

- We add one new runner to the YAML (provider-agnostic) which only runs on an r-release branch. 
- `fledge::unleash()` is added to `tic.R` for one runner. By default it will do nothing until it detects a tagged build: then it opens an `r-release` branch. (This also means the tagging would happen before we release to CRAN. In your last comment you want to tag in `post_release()`?)
- This config calls again `fledge::unleash()` which will now execute `pre_release()` internally since it detected a release branch. 
- Next, if the user checks all boxes in `cran-comments.md` and commits/pushes the release branch, `fledge::unleash()` will call `fledge::release()` and we continue.
- After acceptance, the same run could be re-run and `fledge::unleash()` should detect the "accepted state" and call `fledge::post_release()`.

AFAIR we wanted a tag (triggered by a GitHub release) to be the starting point for `fledge::unleash()` - did we change on this idea?

**Comment by krlmlr** [comment] 2020-07-31 17:17
We have two kinds of tag -- for the library, and for the R package. The library tag triggers the first `unleash()`, which opens up a branch and a pull request. Subsequent calls to `unleash()` operate only on that branch. Not sure about what triggers the final `unleash()` -- maybe a merge of the pull request?

Implementation plan:

- [ ] Implement a rough draft of `unleash()` (so far only `pre_release()` needs to work)
- [ ] Test manually
- [ ] Set up an entry in the build matrix that is triggered by a tag and by CRAN branches and calls `unleash()`
- [ ] Refine implementation of `unleash()` as needed

**Comment by alanpaulkwan** [comment] 2020-08-30 01:21
On a related note, if I wanted to get the latest version on Github, right now the instructions are not viable. This returns 404. 

http://download.duckdb.org/alias/master/rstats/

**Comment by hannesmuehleisen** [comment] 2020-08-30 05:46
@alanpaulkwan yes we are going to change this to the CRAN install method once its approved.

**Closed** 2021-02-15 21:14 UTC
Labels: R
