### ISSUE TITLE
Updated value in column is not visible in a SELECT

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#579] opened 2020-04-24 08:25 UTC
Consider the following statements:
```sql
CREATE TABLE t0(c0 VARCHAR, c1 VARCHAR);
INSERT INTO t0(c0) VALUES(0), ('');
UPDATE t0 SET c1 = 1;
SELECT t0.c1 FROM t0 WHERE '' = t0.c0; -- expected: {1}, actual: {''}
```
Unexpectedly, the updated value is not visible in the `SELECT`. When, for example, removing the `WHERE` clause, the expected values are printed (namely `{1, 1}`).

I found this based on the latest master commit (ed92e9c55), and can also reproduce it based on the latest fix branch (251c0aa44).

**Comment by Mytherin** [comment] 2020-04-24 08:32
I can't seem to reproduce it as is, did you perhaps accidentally remove the `WHERE` clause from the example?

**Comment by mrigger** [comment] 2020-04-24 08:34
Yes, sorry! I've updated the bug report.

**Comment by Mytherin** [comment] 2020-04-24 08:35
Thanks :)

**Comment by pdet** [comment] 2020-04-25 10:08
The problem was that when we had selections on tables with updates strings, the update_counter would not be incremented correctly, hence the scan would skip the updated data, and just look at the old state.

**Comment by pdet** [comment] 2020-04-25 10:10
I've closed this issue since I've updated rigger8 with the fix, but @Mytherin might want to only close it only after being merged in the master branch :-).

**Closed** 2020-04-26 19:11 UTC
