### ISSUE TITLE
UPDATE on altered table results in an error "Could not find node in column segment tree"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#622] opened 2020-05-05 09:13 UTC
Consider the following statements:
```sql
CREATE TABLE t0(c0 TIMESTAMP);
INSERT INTO t0 VALUES(NULL);
DELETE FROM t0;
ALTER TABLE t0 ALTER c0 TYPE DATE;
INSERT INTO t0 VALUES(NULL);
UPDATE t0 SET c0 = '1969-12-18'; -- Error: Could not find node in column segment tree!
```
Unexpectedly, the `UPDATE` results in an error `Error: Could not find node in column segment tree!`. I found this based on commit 0e4b94f958b120fdaad45bda594933a2b84fced5, and can also reproduce it in the latest fix branch on commit 6ef7f2f0202d9d6a8556de022dbe3c9d02851eb5.

**Comment by Mytherin** [comment] 2020-05-05 09:28
Thanks again, fixed now :)

The problem was that in the ALTER TYPE scan, we only converted tuples that were not marked as deleted. In principle this is fine, however, the problem was that the columns became misaligned internally. 

For example, if we had two columns:
```
C1: [1 2]
C2: [2 3]
```

We deleted a row:
```
C1: [X 2]
C2: [X 3]
```
Then we called ALTER TYPE on the second column, the result would be this:
```
C1: [X 2]
C2: [3]
```
While the correct values are all there, the problem is that we keep track of these row ids on the table level. This then goes wrong, as the table looks for "rowid 1", but the second column only has a single entry, thus it can only look for "rowid 0".

I fixed this by also converting deleted tuples, so the alignment between columns is not broken.

**Closed** 2020-05-06 10:44 UTC
