### ISSUE TITLE
Incorrect result for predicate with shift on a BIGINT column

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#538] opened 2020-04-12 20:53 UTC
Consider the following statements:
```sql
CREATE TABLE t0(c0 BIGINT);
INSERT INTO t0(c0) VALUES (-1);
INSERT INTO t0(c0) VALUES (0);
SELECT * FROM t0 WHERE t0.c0 AND (t0.c0<<64);-- expected: {}, actual: {-1}
``` 
The following seems to indicate that the predicate should evaluate to `FALSE` on both rows:
```sql
SELECT t0.c0 AND (t0.c0<<64) FROM t0; -- {false, false}
```

I found this bug based on commit 3f0eb5134512c6097805998ccc5eb44476534736.

**Comment by Mytherin** [comment] 2020-04-13 12:33
Fixed in faf41956b6363882ef217b81e0c0db9fb7f39970, likely caused by undefined behavior from shifting by a too big value.

**Closed** 2020-04-13 19:35 UTC
